name: Django application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build: 
   name: build docker images
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v3
      
   
  
   - name: Build Docker Image   
     env:
        DOCKER_USER: '${{ secrets.DOCKER_USER }}'
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'    
     run: |
            - docker build -f Dockerfile -t vyasg84/djnago-todo-app:latest .
            - docker build -t vyasg84/nginx-todo -f Dockerfile.nginx .
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker push docker.io/vyasg84/djnago-todo-app:latest
            - docker push docker.io/vyasg84/nginx-todo:latest
    
